//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.03 at 12:29:04 PM GMT+01:00 
//


package stm.vis.data.area;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for countryType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="countryType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="SE"/>
 *     &lt;enumeration value="RU"/>
 *     &lt;enumeration value="GB"/>
 *     &lt;enumeration value="DK"/>
 *     &lt;enumeration value="FI"/>
 *     &lt;enumeration value="NO"/>
 *     &lt;enumeration value="EE"/>
 *     &lt;enumeration value="LV"/>
 *     &lt;enumeration value="LT"/>
 *     &lt;enumeration value="PL"/>
 *     &lt;enumeration value="DE"/>
 *     &lt;enumeration value="ES"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "countryType", namespace = "http://www.iho.int/S124/gml/1.0")
@XmlEnum
public enum CountryType {

    SE,
    RU,
    GB,
    DK,
    FI,
    NO,
    EE,
    LV,
    LT,
    PL,
    DE,
    ES;

    public String value() {
        return name();
    }

    public static CountryType fromValue(String v) {
        return valueOf(v);
    }

}
