//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.03 at 12:29:04 PM GMT+01:00 
//


package stm.vis.data.area;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * Dataset element for Navigational Warnings dataset as "GML document"
 * 
 * <p>Java class for DatasetType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DatasetType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.opengis.net/gml/3.2}AbstractFeatureType">
 *       &lt;sequence>
 *         &lt;element name="DatasetIdentificationInformation" type="{http://www.iho.int/s100gml/1.0}DataSetIdentificationType" minOccurs="0"/>
 *         &lt;element name="DatasetStructureInformation" type="{http://www.iho.int/s100gml/1.0}DataSetStructureInformationType" minOccurs="0"/>
 *         &lt;group ref="{http://www.iho.int/s100gml/1.0}Geometry" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;choice maxOccurs="unbounded" minOccurs="0">
 *           &lt;element name="imember" type="{http://www.iho.int/S124/gml/1.0}IMemberType" maxOccurs="unbounded" minOccurs="0"/>
 *           &lt;element name="member" type="{http://www.iho.int/S124/gml/1.0}MemberType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DatasetType", namespace = "http://www.iho.int/S124/gml/1.0", propOrder = {
    "datasetIdentificationInformation",
    "datasetStructureInformation",
    "geometry",
    "imemberOrMember"
})
public class DatasetType
    extends AbstractFeatureType
{

    @XmlElement(name = "DatasetIdentificationInformation", namespace = "")
    protected DataSetIdentificationType datasetIdentificationInformation;
    @XmlElement(name = "DatasetStructureInformation", namespace = "")
    protected DataSetStructureInformationType datasetStructureInformation;
    @XmlElements({
        @XmlElement(name = "Point", namespace = "http://www.iho.int/s100gml/1.0", type = PointType.class),
        @XmlElement(name = "MultiPoint", namespace = "http://www.iho.int/s100gml/1.0", type = MultiPointType.class),
        @XmlElement(name = "Curve", namespace = "http://www.iho.int/s100gml/1.0", type = CurveType.class),
        @XmlElement(name = "CompositeCurve", namespace = "http://www.iho.int/s100gml/1.0", type = CompositeCurveType.class),
        @XmlElement(name = "OrientableCurve", namespace = "http://www.iho.int/s100gml/1.0", type = OrientableCurveType.class),
        @XmlElement(name = "Surface", namespace = "http://www.iho.int/s100gml/1.0", type = SurfaceType.class),
        @XmlElement(name = "Polygon", namespace = "http://www.iho.int/s100gml/1.0", type = PolygonType.class)
    })
    protected List<AbstractGeometryType> geometry;
    @XmlElements({
        @XmlElement(name = "imember", namespace = "", type = IMemberType.class),
        @XmlElement(name = "member", namespace = "", type = MemberType.class)
    })
    protected List<AbstractFeatureMemberType> imemberOrMember;

    /**
     * Gets the value of the datasetIdentificationInformation property.
     * 
     * @return
     *     possible object is
     *     {@link DataSetIdentificationType }
     *     
     */
    public DataSetIdentificationType getDatasetIdentificationInformation() {
        return datasetIdentificationInformation;
    }

    /**
     * Sets the value of the datasetIdentificationInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataSetIdentificationType }
     *     
     */
    public void setDatasetIdentificationInformation(DataSetIdentificationType value) {
        this.datasetIdentificationInformation = value;
    }

    /**
     * Gets the value of the datasetStructureInformation property.
     * 
     * @return
     *     possible object is
     *     {@link DataSetStructureInformationType }
     *     
     */
    public DataSetStructureInformationType getDatasetStructureInformation() {
        return datasetStructureInformation;
    }

    /**
     * Sets the value of the datasetStructureInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataSetStructureInformationType }
     *     
     */
    public void setDatasetStructureInformation(DataSetStructureInformationType value) {
        this.datasetStructureInformation = value;
    }

    /**
     * Allows spatial objects to be located outside feature objects (for references, and compatibility with ISO 8211 encoding) Gets the value of the geometry property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the geometry property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGeometry().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PointType }
     * {@link MultiPointType }
     * {@link CurveType }
     * {@link CompositeCurveType }
     * {@link OrientableCurveType }
     * {@link SurfaceType }
     * {@link PolygonType }
     * 
     * 
     */
    public List<AbstractGeometryType> getGeometry() {
        if (geometry == null) {
            geometry = new ArrayList<AbstractGeometryType>();
        }
        return this.geometry;
    }

    /**
     * Gets the value of the imemberOrMember property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the imemberOrMember property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getImemberOrMember().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IMemberType }
     * {@link MemberType }
     * 
     * 
     */
    public List<AbstractFeatureMemberType> getImemberOrMember() {
        if (imemberOrMember == null) {
            imemberOrMember = new ArrayList<AbstractFeatureMemberType>();
        }
        return this.imemberOrMember;
    }

}
