//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.03 at 12:29:04 PM GMT+01:00 
//


package stm.vis.data.area;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Complex type for feature object identifier combines agency, FIDN, FIDS
 * 
 * <p>Java class for FeatureObjectIdentifier complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FeatureObjectIdentifier">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="agency" type="{http://www.iho.int/s100gml/1.0}AgencyCodeType"/>
 *         &lt;element name="featureIdentificationNumber" type="{http://www.iho.int/s100gml/1.0}IdentificationNumberType"/>
 *         &lt;element name="featureIdentificationSubdivision" type="{http://www.iho.int/s100gml/1.0}IdentificationSubdivisionType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FeatureObjectIdentifier", namespace = "http://www.iho.int/s100gml/1.0", propOrder = {
    "agency",
    "featureIdentificationNumber",
    "featureIdentificationSubdivision"
})
public class FeatureObjectIdentifier {

    @XmlElement(required = true)
    protected String agency;
    protected long featureIdentificationNumber;
    protected int featureIdentificationSubdivision;

    /**
     * Gets the value of the agency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgency() {
        return agency;
    }

    /**
     * Sets the value of the agency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgency(String value) {
        this.agency = value;
    }

    /**
     * Gets the value of the featureIdentificationNumber property.
     * 
     */
    public long getFeatureIdentificationNumber() {
        return featureIdentificationNumber;
    }

    /**
     * Sets the value of the featureIdentificationNumber property.
     * 
     */
    public void setFeatureIdentificationNumber(long value) {
        this.featureIdentificationNumber = value;
    }

    /**
     * Gets the value of the featureIdentificationSubdivision property.
     * 
     */
    public int getFeatureIdentificationSubdivision() {
        return featureIdentificationSubdivision;
    }

    /**
     * Sets the value of the featureIdentificationSubdivision property.
     * 
     */
    public void setFeatureIdentificationSubdivision(int value) {
        this.featureIdentificationSubdivision = value;
    }

}
