//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.03 at 12:29:04 PM GMT+01:00 
//


package stm.vis.data.area;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the stm.vis.data.area package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Surface_QNAME = new QName("http://www.opengis.net/gml/3.2", "Surface");
    private final static QName _PolygonProperty_QNAME = new QName("http://www.iho.int/s100gml/1.0", "polygonProperty");
    private final static QName _GmlProfileGmlProfileSchema_QNAME = new QName("http://www.opengis.net/gml/3.2", "gmlProfileSchema");
    private final static QName _GmlProfilePoint_QNAME = new QName("http://www.opengis.net/gml/3.2", "Point");
    private final static QName _Resource_QNAME = new QName("http://www.w3.org/1999/xlink", "resource");
    private final static QName _SurfaceProperty_QNAME = new QName("http://www.iho.int/s100gml/1.0", "surfaceProperty");
    private final static QName _S124References_QNAME = new QName("http://www.iho.int/S124/gml/1.0", "S124_References");
    private final static QName _AbstractAssociationRole_QNAME = new QName("http://www.opengis.net/gml/3.2", "abstractAssociationRole");
    private final static QName _AbstractSurfacePatch_QNAME = new QName("http://www.opengis.net/gml/3.2", "AbstractSurfacePatch");
    private final static QName _LinearRing_QNAME = new QName("http://www.opengis.net/gml/3.2", "LinearRing");
    private final static QName _AbstractFeature_QNAME = new QName("http://www.opengis.net/gml/3.2", "AbstractFeature");
    private final static QName _S124NavigationalWarningPart_QNAME = new QName("http://www.iho.int/S124/gml/1.0", "S124_NavigationalWarningPart");
    private final static QName _InvFeatureAssociation_QNAME = new QName("http://www.iho.int/s100gml/1.0", "invFeatureAssociation");
    private final static QName _Pos_QNAME = new QName("http://www.opengis.net/gml/3.2", "pos");
    private final static QName _LineStringSegment_QNAME = new QName("http://www.opengis.net/gml/3.2", "LineStringSegment");
    private final static QName _AbstractObject_QNAME = new QName("http://www.opengis.net/gml/3.2", "AbstractObject");
    private final static QName _GmlBasePolygon_QNAME = new QName("http://www.iho.int/s100gml/1.0", "Polygon");
    private final static QName _AbstractGML_QNAME = new QName("http://www.opengis.net/gml/3.2", "AbstractGML");
    private final static QName _Interior_QNAME = new QName("http://www.opengis.net/gml/3.2", "interior");
    private final static QName _Exterior_QNAME = new QName("http://www.opengis.net/gml/3.2", "exterior");
    private final static QName _AbstractRing_QNAME = new QName("http://www.opengis.net/gml/3.2", "AbstractRing");
    private final static QName _GmlProfileSchema_QNAME = new QName("http://www.iho.int/S-100/profile/s100_gmlProfile", "gmlProfileSchema");
    private final static QName _DefaultCodeSpace_QNAME = new QName("http://www.opengis.net/gml/3.2", "defaultCodeSpace");
    private final static QName _AbstractGeometricPrimitive_QNAME = new QName("http://www.opengis.net/gml/3.2", "AbstractGeometricPrimitive");
    private final static QName _OrientableCurve_QNAME = new QName("http://www.iho.int/s100gml/1.0", "OrientableCurve");
    private final static QName _S124InformationType_QNAME = new QName("http://www.iho.int/S124/gml/1.0", "S124_InformationType");
    private final static QName _GmlProfilePointProperty_QNAME = new QName("http://www.opengis.net/gml/3.2", "pointProperty");
    private final static QName _GmlProfileCompositeCurve_QNAME = new QName("http://www.opengis.net/gml/3.2", "CompositeCurve");
    private final static QName _DataSet_QNAME = new QName("http://www.iho.int/S124/gml/1.0", "DataSet");
    private final static QName _Patches_QNAME = new QName("http://www.opengis.net/gml/3.2", "patches");
    private final static QName _BoundedBy_QNAME = new QName("http://www.opengis.net/gml/3.2", "boundedBy");
    private final static QName _GmlProfileCurve_QNAME = new QName("http://www.opengis.net/gml/3.2", "Curve");
    private final static QName _OrientableCurveProperty_QNAME = new QName("http://www.iho.int/s100gml/1.0", "orientableCurveProperty");
    private final static QName _AbstractInlineProperty_QNAME = new QName("http://www.opengis.net/gml/3.2", "abstractInlineProperty");
    private final static QName _AbstractCurve_QNAME = new QName("http://www.opengis.net/gml/3.2", "AbstractCurve");
    private final static QName _GmlBaseMultiPoint_QNAME = new QName("http://www.iho.int/s100gml/1.0", "MultiPoint");
    private final static QName _Title_QNAME = new QName("http://www.w3.org/1999/xlink", "title");
    private final static QName _AbstractValue_QNAME = new QName("http://www.opengis.net/gml/3.2", "AbstractValue");
    private final static QName _S124NWPreamble_QNAME = new QName("http://www.iho.int/S124/gml/1.0", "S124_NWPreamble");
    private final static QName _ComplianceLevel_QNAME = new QName("http://www.iho.int/S-100/profile/s100_gmlProfile", "complianceLevel");
    private final static QName _AbstractScalarValue_QNAME = new QName("http://www.opengis.net/gml/3.2", "AbstractScalarValue");
    private final static QName _ReversePropertyName_QNAME = new QName("http://www.opengis.net/gml/3.2", "reversePropertyName");
    private final static QName _S100ArcByCenterPoint_QNAME = new QName("http://www.iho.int/s100gml/1.0", "S100_ArcByCenterPoint");
    private final static QName _MultiPoint_QNAME = new QName("http://www.opengis.net/gml/3.2", "MultiPoint");
    private final static QName _AbstractReference_QNAME = new QName("http://www.opengis.net/gml/3.2", "abstractReference");
    private final static QName _BaseCurve_QNAME = new QName("http://www.opengis.net/gml/3.2", "baseCurve");
    private final static QName _InvInformationAssociation_QNAME = new QName("http://www.iho.int/s100gml/1.0", "invInformationAssociation");
    private final static QName _TargetElement_QNAME = new QName("http://www.opengis.net/gml/3.2", "targetElement");
    private final static QName _Locator_QNAME = new QName("http://www.w3.org/1999/xlink", "locator");
    private final static QName _AbstractGeometry_QNAME = new QName("http://www.opengis.net/gml/3.2", "AbstractGeometry");
    private final static QName _PointMember_QNAME = new QName("http://www.opengis.net/gml/3.2", "pointMember");
    private final static QName _GmlProfileOrientableCurve_QNAME = new QName("http://www.opengis.net/gml/3.2", "OrientableCurve");
    private final static QName _PointProperty_QNAME = new QName("http://www.iho.int/s100gml/1.0", "pointProperty");
    private final static QName _GmlBaseCompositeCurve_QNAME = new QName("http://www.iho.int/s100gml/1.0", "CompositeCurve");
    private final static QName _S100CircleByCenterPoint_QNAME = new QName("http://www.iho.int/s100gml/1.0", "S100_CircleByCenterPoint");
    private final static QName _MultiPointProperty_QNAME = new QName("http://www.iho.int/s100gml/1.0", "multiPointProperty");
    private final static QName _InformationAssociation_QNAME = new QName("http://www.iho.int/s100gml/1.0", "informationAssociation");
    private final static QName _Ring_QNAME = new QName("http://www.opengis.net/gml/3.2", "Ring");
    private final static QName _Segments_QNAME = new QName("http://www.opengis.net/gml/3.2", "segments");
    private final static QName _Measure_QNAME = new QName("http://www.opengis.net/gml/3.2", "measure");
    private final static QName _Curve_QNAME = new QName("http://www.iho.int/s100gml/1.0", "Curve");
    private final static QName _AbstractSurface_QNAME = new QName("http://www.opengis.net/gml/3.2", "AbstractSurface");
    private final static QName _GeodesicString_QNAME = new QName("http://www.opengis.net/gml/3.2", "GeodesicString");
    private final static QName _AssociationName_QNAME = new QName("http://www.opengis.net/gml/3.2", "associationName");
    private final static QName _S124FeatureType_QNAME = new QName("http://www.iho.int/S124/gml/1.0", "S124_FeatureType");
    private final static QName _Polygon_QNAME = new QName("http://www.opengis.net/gml/3.2", "Polygon");
    private final static QName _CompositeCurveProperty_QNAME = new QName("http://www.iho.int/s100gml/1.0", "compositeCurveProperty");
    private final static QName _S124InformationNoticePart_QNAME = new QName("http://www.iho.int/S124/gml/1.0", "S124_InformationNoticePart");
    private final static QName _PolygonPatch_QNAME = new QName("http://www.opengis.net/gml/3.2", "PolygonPatch");
    private final static QName _LineString_QNAME = new QName("http://www.opengis.net/gml/3.2", "LineString");
    private final static QName _GmlBaseSurface_QNAME = new QName("http://www.iho.int/s100gml/1.0", "Surface");
    private final static QName _Boolean_QNAME = new QName("http://www.opengis.net/gml/3.2", "Boolean");
    private final static QName _Point_QNAME = new QName("http://www.iho.int/s100gml/1.0", "Point");
    private final static QName _Geodesic_QNAME = new QName("http://www.opengis.net/gml/3.2", "Geodesic");
    private final static QName _Angle_QNAME = new QName("http://www.opengis.net/gml/3.2", "angle");
    private final static QName _CurveProperty_QNAME = new QName("http://www.iho.int/s100gml/1.0", "curveProperty");
    private final static QName _Arc_QNAME = new QName("http://www.w3.org/1999/xlink", "arc");
    private final static QName _PosList_QNAME = new QName("http://www.opengis.net/gml/3.2", "posList");
    private final static QName _AbstractCurveSegment_QNAME = new QName("http://www.opengis.net/gml/3.2", "AbstractCurveSegment");
    private final static QName _FeatureAssociation_QNAME = new QName("http://www.iho.int/s100gml/1.0", "featureAssociation");
    private final static QName _AbstractGeometricAggregate_QNAME = new QName("http://www.opengis.net/gml/3.2", "AbstractGeometricAggregate");
    private final static QName _CurveMember_QNAME = new QName("http://www.opengis.net/gml/3.2", "curveMember");
    private final static QName _Envelope_QNAME = new QName("http://www.opengis.net/gml/3.2", "Envelope");
    private final static QName _S124FeatureTypeTypeId_QNAME = new QName("", "id");
    private final static QName _S124FeatureTypeTypeAreaAffected_QNAME = new QName("", "areaAffected");
    private final static QName _S124FeatureTypeTypeRadius_QNAME = new QName("", "radius");
    private final static QName _S124FeatureTypeTypeExtReferenceId_QNAME = new QName("", "extReferenceId");
    private final static QName _S124FeatureTypeTypeGeometry_QNAME = new QName("", "geometry");
    private final static QName _S124InformationTypeTypeProvides_QNAME = new QName("", "provides");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: stm.vis.data.area
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link S124NavigationalWarningPartType }
     * 
     */
    public S124NavigationalWarningPartType createS124NavigationalWarningPartType() {
        return new S124NavigationalWarningPartType();
    }

    /**
     * Create an instance of {@link DatasetType }
     * 
     */
    public DatasetType createDatasetType() {
        return new DatasetType();
    }

    /**
     * Create an instance of {@link S124NWPreambleType }
     * 
     */
    public S124NWPreambleType createS124NWPreambleType() {
        return new S124NWPreambleType();
    }

    /**
     * Create an instance of {@link S124ReferencesType }
     * 
     */
    public S124ReferencesType createS124ReferencesType() {
        return new S124ReferencesType();
    }

    /**
     * Create an instance of {@link S124InformationNoticePartType }
     * 
     */
    public S124InformationNoticePartType createS124InformationNoticePartType() {
        return new S124InformationNoticePartType();
    }

    /**
     * Create an instance of {@link S124MessageSeriesIdentifierType }
     * 
     */
    public S124MessageSeriesIdentifierType createS124MessageSeriesIdentifierType() {
        return new S124MessageSeriesIdentifierType();
    }

    /**
     * Create an instance of {@link CurveOrSurface }
     * 
     */
    public CurveOrSurface createCurveOrSurface() {
        return new CurveOrSurface();
    }

    /**
     * Create an instance of {@link S124LocalizedTextType }
     * 
     */
    public S124LocalizedTextType createS124LocalizedTextType() {
        return new S124LocalizedTextType();
    }

    /**
     * Create an instance of {@link S124AffectedChartType }
     * 
     */
    public S124AffectedChartType createS124AffectedChartType() {
        return new S124AffectedChartType();
    }

    /**
     * Create an instance of {@link PointOrSurface }
     * 
     */
    public PointOrSurface createPointOrSurface() {
        return new PointOrSurface();
    }

    /**
     * Create an instance of {@link GMPoint }
     * 
     */
    public GMPoint createGMPoint() {
        return new GMPoint();
    }

    /**
     * Create an instance of {@link PointCurveSurface }
     * 
     */
    public PointCurveSurface createPointCurveSurface() {
        return new PointCurveSurface();
    }

    /**
     * Create an instance of {@link CancellationTimeType }
     * 
     */
    public CancellationTimeType createCancellationTimeType() {
        return new CancellationTimeType();
    }

    /**
     * Create an instance of {@link IMemberType }
     * 
     */
    public IMemberType createIMemberType() {
        return new IMemberType();
    }

    /**
     * Create an instance of {@link PointOrCurve }
     * 
     */
    public PointOrCurve createPointOrCurve() {
        return new PointOrCurve();
    }

    /**
     * Create an instance of {@link FixedDateRangeType }
     * 
     */
    public FixedDateRangeType createFixedDateRangeType() {
        return new FixedDateRangeType();
    }

    /**
     * Create an instance of {@link GMCurve }
     * 
     */
    public GMCurve createGMCurve() {
        return new GMCurve();
    }

    /**
     * Create an instance of {@link S100TruncatedDate }
     * 
     */
    public S100TruncatedDate createS100TruncatedDate() {
        return new S100TruncatedDate();
    }

    /**
     * Create an instance of {@link MemberType }
     * 
     */
    public MemberType createMemberType() {
        return new MemberType();
    }

    /**
     * Create an instance of {@link GMSurface }
     * 
     */
    public GMSurface createGMSurface() {
        return new GMSurface();
    }

    /**
     * Create an instance of {@link SurfacePropertyType }
     * 
     */
    public SurfacePropertyType createSurfacePropertyType() {
        return new SurfacePropertyType();
    }

    /**
     * Create an instance of {@link InverseInformationAssociationType }
     * 
     */
    public InverseInformationAssociationType createInverseInformationAssociationType() {
        return new InverseInformationAssociationType();
    }

    /**
     * Create an instance of {@link OrientableCurvePropertyType }
     * 
     */
    public OrientableCurvePropertyType createOrientableCurvePropertyType() {
        return new OrientableCurvePropertyType();
    }

    /**
     * Create an instance of {@link CompositeCurvePropertyType }
     * 
     */
    public CompositeCurvePropertyType createCompositeCurvePropertyType() {
        return new CompositeCurvePropertyType();
    }

    /**
     * Create an instance of {@link PolygonPropertyType }
     * 
     */
    public PolygonPropertyType createPolygonPropertyType() {
        return new PolygonPropertyType();
    }

    /**
     * Create an instance of {@link OrientableCurveType }
     * 
     */
    public OrientableCurveType createOrientableCurveType() {
        return new OrientableCurveType();
    }

    /**
     * Create an instance of {@link S100ArcByCenterPointType }
     * 
     */
    public S100ArcByCenterPointType createS100ArcByCenterPointType() {
        return new S100ArcByCenterPointType();
    }

    /**
     * Create an instance of {@link InformationPropertyType }
     * 
     */
    public InformationPropertyType createInformationPropertyType() {
        return new InformationPropertyType();
    }

    /**
     * Create an instance of {@link MultiPointPropertyType }
     * 
     */
    public MultiPointPropertyType createMultiPointPropertyType() {
        return new MultiPointPropertyType();
    }

    /**
     * Create an instance of {@link PolygonType }
     * 
     */
    public PolygonType createPolygonType() {
        return new PolygonType();
    }

    /**
     * Create an instance of {@link PolygonType2 }
     * 
     */
    public PolygonType2 createPolygonType2() {
        return new PolygonType2();
    }

    /**
     * Create an instance of {@link CurveType }
     * 
     */
    public CurveType createCurveType() {
        return new CurveType();
    }

    /**
     * Create an instance of {@link CurveType2 }
     * 
     */
    public CurveType2 createCurveType2() {
        return new CurveType2();
    }

    /**
     * Create an instance of {@link FeaturePropertyType }
     * 
     */
    public FeaturePropertyType createFeaturePropertyType() {
        return new FeaturePropertyType();
    }

    /**
     * Create an instance of {@link SurfaceType }
     * 
     */
    public SurfaceType createSurfaceType() {
        return new SurfaceType();
    }

    /**
     * Create an instance of {@link SurfaceType2 }
     * 
     */
    public SurfaceType2 createSurfaceType2() {
        return new SurfaceType2();
    }

    /**
     * Create an instance of {@link S100CircleByCenterPointType }
     * 
     */
    public S100CircleByCenterPointType createS100CircleByCenterPointType() {
        return new S100CircleByCenterPointType();
    }

    /**
     * Create an instance of {@link MultiPointType }
     * 
     */
    public MultiPointType createMultiPointType() {
        return new MultiPointType();
    }

    /**
     * Create an instance of {@link CurvePropertyType }
     * 
     */
    public CurvePropertyType createCurvePropertyType() {
        return new CurvePropertyType();
    }

    /**
     * Create an instance of {@link PointType }
     * 
     */
    public PointType createPointType() {
        return new PointType();
    }

    /**
     * Create an instance of {@link PointPropertyType }
     * 
     */
    public PointPropertyType createPointPropertyType() {
        return new PointPropertyType();
    }

    /**
     * Create an instance of {@link CompositeCurveType }
     * 
     */
    public CompositeCurveType createCompositeCurveType() {
        return new CompositeCurveType();
    }

    /**
     * Create an instance of {@link AbstractFeatureType2 }
     * 
     */
    public AbstractFeatureType2 createAbstractFeatureType2() {
        return new AbstractFeatureType2();
    }

    /**
     * Create an instance of {@link AbstractInformationType }
     * 
     */
    public AbstractInformationType createAbstractInformationType() {
        return new AbstractInformationType();
    }

    /**
     * Create an instance of {@link DataSetStructureInformationType }
     * 
     */
    public DataSetStructureInformationType createDataSetStructureInformationType() {
        return new DataSetStructureInformationType();
    }

    /**
     * Create an instance of {@link FeatureObjectIdentifier }
     * 
     */
    public FeatureObjectIdentifier createFeatureObjectIdentifier() {
        return new FeatureObjectIdentifier();
    }

    /**
     * Create an instance of {@link DataSetIdentificationType }
     * 
     */
    public DataSetIdentificationType createDataSetIdentificationType() {
        return new DataSetIdentificationType();
    }

    /**
     * Create an instance of {@link AbstractRingPropertyType }
     * 
     */
    public AbstractRingPropertyType createAbstractRingPropertyType() {
        return new AbstractRingPropertyType();
    }

    /**
     * Create an instance of {@link LinearRingType }
     * 
     */
    public LinearRingType createLinearRingType() {
        return new LinearRingType();
    }

    /**
     * Create an instance of {@link DirectPositionType }
     * 
     */
    public DirectPositionType createDirectPositionType() {
        return new DirectPositionType();
    }

    /**
     * Create an instance of {@link LineStringSegmentType }
     * 
     */
    public LineStringSegmentType createLineStringSegmentType() {
        return new LineStringSegmentType();
    }

    /**
     * Create an instance of {@link AssociationRoleType }
     * 
     */
    public AssociationRoleType createAssociationRoleType() {
        return new AssociationRoleType();
    }

    /**
     * Create an instance of {@link PointType2 }
     * 
     */
    public PointType2 createPointType2() {
        return new PointType2();
    }

    /**
     * Create an instance of {@link InlinePropertyType }
     * 
     */
    public InlinePropertyType createInlinePropertyType() {
        return new InlinePropertyType();
    }

    /**
     * Create an instance of {@link BoundingShapeType }
     * 
     */
    public BoundingShapeType createBoundingShapeType() {
        return new BoundingShapeType();
    }

    /**
     * Create an instance of {@link SurfacePatchArrayPropertyType }
     * 
     */
    public SurfacePatchArrayPropertyType createSurfacePatchArrayPropertyType() {
        return new SurfacePatchArrayPropertyType();
    }

    /**
     * Create an instance of {@link PointPropertyType2 }
     * 
     */
    public PointPropertyType2 createPointPropertyType2() {
        return new PointPropertyType2();
    }

    /**
     * Create an instance of {@link CompositeCurveType2 }
     * 
     */
    public CompositeCurveType2 createCompositeCurveType2() {
        return new CompositeCurveType2();
    }

    /**
     * Create an instance of {@link MeasureType }
     * 
     */
    public MeasureType createMeasureType() {
        return new MeasureType();
    }

    /**
     * Create an instance of {@link CurveSegmentArrayPropertyType }
     * 
     */
    public CurveSegmentArrayPropertyType createCurveSegmentArrayPropertyType() {
        return new CurveSegmentArrayPropertyType();
    }

    /**
     * Create an instance of {@link RingType }
     * 
     */
    public RingType createRingType() {
        return new RingType();
    }

    /**
     * Create an instance of {@link CurvePropertyType2 }
     * 
     */
    public CurvePropertyType2 createCurvePropertyType2() {
        return new CurvePropertyType2();
    }

    /**
     * Create an instance of {@link ReferenceType }
     * 
     */
    public ReferenceType createReferenceType() {
        return new ReferenceType();
    }

    /**
     * Create an instance of {@link MultiPointType2 }
     * 
     */
    public MultiPointType2 createMultiPointType2() {
        return new MultiPointType2();
    }

    /**
     * Create an instance of {@link DirectPositionListType }
     * 
     */
    public DirectPositionListType createDirectPositionListType() {
        return new DirectPositionListType();
    }

    /**
     * Create an instance of {@link EnvelopeType }
     * 
     */
    public EnvelopeType createEnvelopeType() {
        return new EnvelopeType();
    }

    /**
     * Create an instance of {@link LineStringType }
     * 
     */
    public LineStringType createLineStringType() {
        return new LineStringType();
    }

    /**
     * Create an instance of {@link PolygonPatchType }
     * 
     */
    public PolygonPatchType createPolygonPatchType() {
        return new PolygonPatchType();
    }

    /**
     * Create an instance of {@link Boolean }
     * 
     */
    public Boolean createBoolean() {
        return new Boolean();
    }

    /**
     * Create an instance of {@link GeodesicType }
     * 
     */
    public GeodesicType createGeodesicType() {
        return new GeodesicType();
    }

    /**
     * Create an instance of {@link GeodesicStringType }
     * 
     */
    public GeodesicStringType createGeodesicStringType() {
        return new GeodesicStringType();
    }

    /**
     * Create an instance of {@link AngleType }
     * 
     */
    public AngleType createAngleType() {
        return new AngleType();
    }

    /**
     * Create an instance of {@link CodeWithAuthorityType }
     * 
     */
    public CodeWithAuthorityType createCodeWithAuthorityType() {
        return new CodeWithAuthorityType();
    }

    /**
     * Create an instance of {@link VolumeType }
     * 
     */
    public VolumeType createVolumeType() {
        return new VolumeType();
    }

    /**
     * Create an instance of {@link CodeType }
     * 
     */
    public CodeType createCodeType() {
        return new CodeType();
    }

    /**
     * Create an instance of {@link SurfacePropertyType2 }
     * 
     */
    public SurfacePropertyType2 createSurfacePropertyType2() {
        return new SurfacePropertyType2();
    }

    /**
     * Create an instance of {@link GeometricPrimitivePropertyType }
     * 
     */
    public GeometricPrimitivePropertyType createGeometricPrimitivePropertyType() {
        return new GeometricPrimitivePropertyType();
    }

    /**
     * Create an instance of {@link LinearRingPropertyType }
     * 
     */
    public LinearRingPropertyType createLinearRingPropertyType() {
        return new LinearRingPropertyType();
    }

    /**
     * Create an instance of {@link LengthType }
     * 
     */
    public LengthType createLengthType() {
        return new LengthType();
    }

    /**
     * Create an instance of {@link FeaturePropertyType2 }
     * 
     */
    public FeaturePropertyType2 createFeaturePropertyType2() {
        return new FeaturePropertyType2();
    }

    /**
     * Create an instance of {@link LocatorType }
     * 
     */
    public LocatorType createLocatorType() {
        return new LocatorType();
    }

    /**
     * Create an instance of {@link TitleEltType }
     * 
     */
    public TitleEltType createTitleEltType() {
        return new TitleEltType();
    }

    /**
     * Create an instance of {@link ArcType }
     * 
     */
    public ArcType createArcType() {
        return new ArcType();
    }

    /**
     * Create an instance of {@link ResourceType }
     * 
     */
    public ResourceType createResourceType() {
        return new ResourceType();
    }

    /**
     * Create an instance of {@link Simple }
     * 
     */
    public Simple createSimple() {
        return new Simple();
    }

    /**
     * Create an instance of {@link Extended }
     * 
     */
    public Extended createExtended() {
        return new Extended();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SurfaceType2 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/gml/3.2", name = "Surface", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractSurface")
    public JAXBElement<SurfaceType2> createSurface(SurfaceType2 value) {
        return new JAXBElement<SurfaceType2>(_Surface_QNAME, SurfaceType2 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PolygonPropertyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.iho.int/s100gml/1.0", name = "polygonProperty")
    public JAXBElement<PolygonPropertyType> createPolygonProperty(PolygonPropertyType value) {
        return new JAXBElement<PolygonPropertyType>(_PolygonProperty_QNAME, PolygonPropertyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/gml/3.2", name = "gmlProfileSchema")
    public JAXBElement<String> createGmlProfileGmlProfileSchema(String value) {
        return new JAXBElement<String>(_GmlProfileGmlProfileSchema_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PointType2 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/gml/3.2", name = "Point", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractGeometricPrimitive")
    public JAXBElement<PointType2> createGmlProfilePoint(PointType2 value) {
        return new JAXBElement<PointType2>(_GmlProfilePoint_QNAME, PointType2 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResourceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1999/xlink", name = "resource")
    public JAXBElement<ResourceType> createResource(ResourceType value) {
        return new JAXBElement<ResourceType>(_Resource_QNAME, ResourceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SurfacePropertyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.iho.int/s100gml/1.0", name = "surfaceProperty")
    public JAXBElement<SurfacePropertyType> createSurfaceProperty(SurfacePropertyType value) {
        return new JAXBElement<SurfacePropertyType>(_SurfaceProperty_QNAME, SurfacePropertyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link S124ReferencesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.iho.int/S124/gml/1.0", name = "S124_References", substitutionHeadNamespace = "http://www.iho.int/S124/gml/1.0", substitutionHeadName = "S124_InformationType")
    public JAXBElement<S124ReferencesType> createS124References(S124ReferencesType value) {
        return new JAXBElement<S124ReferencesType>(_S124References_QNAME, S124ReferencesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AssociationRoleType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/gml/3.2", name = "abstractAssociationRole")
    public JAXBElement<AssociationRoleType> createAbstractAssociationRole(AssociationRoleType value) {
        return new JAXBElement<AssociationRoleType>(_AbstractAssociationRole_QNAME, AssociationRoleType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractSurfacePatchType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/gml/3.2", name = "AbstractSurfacePatch")
    public JAXBElement<AbstractSurfacePatchType> createAbstractSurfacePatch(AbstractSurfacePatchType value) {
        return new JAXBElement<AbstractSurfacePatchType>(_AbstractSurfacePatch_QNAME, AbstractSurfacePatchType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LinearRingType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/gml/3.2", name = "LinearRing", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractRing")
    public JAXBElement<LinearRingType> createLinearRing(LinearRingType value) {
        return new JAXBElement<LinearRingType>(_LinearRing_QNAME, LinearRingType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractFeatureType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/gml/3.2", name = "AbstractFeature", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractGML")
    public JAXBElement<AbstractFeatureType> createAbstractFeature(AbstractFeatureType value) {
        return new JAXBElement<AbstractFeatureType>(_AbstractFeature_QNAME, AbstractFeatureType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link S124NavigationalWarningPartType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.iho.int/S124/gml/1.0", name = "S124_NavigationalWarningPart", substitutionHeadNamespace = "http://www.iho.int/S124/gml/1.0", substitutionHeadName = "S124_FeatureType")
    public JAXBElement<S124NavigationalWarningPartType> createS124NavigationalWarningPart(S124NavigationalWarningPartType value) {
        return new JAXBElement<S124NavigationalWarningPartType>(_S124NavigationalWarningPart_QNAME, S124NavigationalWarningPartType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FeaturePropertyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.iho.int/s100gml/1.0", name = "invFeatureAssociation")
    public JAXBElement<FeaturePropertyType> createInvFeatureAssociation(FeaturePropertyType value) {
        return new JAXBElement<FeaturePropertyType>(_InvFeatureAssociation_QNAME, FeaturePropertyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DirectPositionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/gml/3.2", name = "pos")
    public JAXBElement<DirectPositionType> createPos(DirectPositionType value) {
        return new JAXBElement<DirectPositionType>(_Pos_QNAME, DirectPositionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LineStringSegmentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/gml/3.2", name = "LineStringSegment", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractCurveSegment")
    public JAXBElement<LineStringSegmentType> createLineStringSegment(LineStringSegmentType value) {
        return new JAXBElement<LineStringSegmentType>(_LineStringSegment_QNAME, LineStringSegmentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/gml/3.2", name = "AbstractObject")
    public JAXBElement<Object> createAbstractObject(Object value) {
        return new JAXBElement<Object>(_AbstractObject_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PolygonType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.iho.int/s100gml/1.0", name = "Polygon", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "Polygon")
    public JAXBElement<PolygonType> createGmlBasePolygon(PolygonType value) {
        return new JAXBElement<PolygonType>(_GmlBasePolygon_QNAME, PolygonType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractGMLType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/gml/3.2", name = "AbstractGML", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractObject")
    public JAXBElement<AbstractGMLType> createAbstractGML(AbstractGMLType value) {
        return new JAXBElement<AbstractGMLType>(_AbstractGML_QNAME, AbstractGMLType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractRingPropertyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/gml/3.2", name = "interior")
    public JAXBElement<AbstractRingPropertyType> createInterior(AbstractRingPropertyType value) {
        return new JAXBElement<AbstractRingPropertyType>(_Interior_QNAME, AbstractRingPropertyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractRingPropertyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/gml/3.2", name = "exterior")
    public JAXBElement<AbstractRingPropertyType> createExterior(AbstractRingPropertyType value) {
        return new JAXBElement<AbstractRingPropertyType>(_Exterior_QNAME, AbstractRingPropertyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractRingType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/gml/3.2", name = "AbstractRing", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractObject")
    public JAXBElement<AbstractRingType> createAbstractRing(AbstractRingType value) {
        return new JAXBElement<AbstractRingType>(_AbstractRing_QNAME, AbstractRingType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.iho.int/S-100/profile/s100_gmlProfile", name = "gmlProfileSchema")
    public JAXBElement<String> createGmlProfileSchema(String value) {
        return new JAXBElement<String>(_GmlProfileSchema_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/gml/3.2", name = "defaultCodeSpace")
    public JAXBElement<String> createDefaultCodeSpace(String value) {
        return new JAXBElement<String>(_DefaultCodeSpace_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractGeometricPrimitiveType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/gml/3.2", name = "AbstractGeometricPrimitive", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractGeometry")
    public JAXBElement<AbstractGeometricPrimitiveType> createAbstractGeometricPrimitive(AbstractGeometricPrimitiveType value) {
        return new JAXBElement<AbstractGeometricPrimitiveType>(_AbstractGeometricPrimitive_QNAME, AbstractGeometricPrimitiveType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrientableCurveType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.iho.int/s100gml/1.0", name = "OrientableCurve", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractCurve")
    public JAXBElement<OrientableCurveType> createOrientableCurve(OrientableCurveType value) {
        return new JAXBElement<OrientableCurveType>(_OrientableCurve_QNAME, OrientableCurveType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link S124InformationTypeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.iho.int/S124/gml/1.0", name = "S124_InformationType")
    public JAXBElement<S124InformationTypeType> createS124InformationType(S124InformationTypeType value) {
        return new JAXBElement<S124InformationTypeType>(_S124InformationType_QNAME, S124InformationTypeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PointPropertyType2 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/gml/3.2", name = "pointProperty")
    public JAXBElement<PointPropertyType2> createGmlProfilePointProperty(PointPropertyType2 value) {
        return new JAXBElement<PointPropertyType2>(_GmlProfilePointProperty_QNAME, PointPropertyType2 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CompositeCurveType2 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/gml/3.2", name = "CompositeCurve", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractCurve")
    public JAXBElement<CompositeCurveType2> createGmlProfileCompositeCurve(CompositeCurveType2 value) {
        return new JAXBElement<CompositeCurveType2>(_GmlProfileCompositeCurve_QNAME, CompositeCurveType2 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DatasetType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.iho.int/S124/gml/1.0", name = "DataSet")
    public JAXBElement<DatasetType> createDataSet(DatasetType value) {
        return new JAXBElement<DatasetType>(_DataSet_QNAME, DatasetType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SurfacePatchArrayPropertyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/gml/3.2", name = "patches")
    public JAXBElement<SurfacePatchArrayPropertyType> createPatches(SurfacePatchArrayPropertyType value) {
        return new JAXBElement<SurfacePatchArrayPropertyType>(_Patches_QNAME, SurfacePatchArrayPropertyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BoundingShapeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/gml/3.2", name = "boundedBy")
    public JAXBElement<BoundingShapeType> createBoundedBy(BoundingShapeType value) {
        return new JAXBElement<BoundingShapeType>(_BoundedBy_QNAME, BoundingShapeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CurveType2 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/gml/3.2", name = "Curve", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractCurve")
    public JAXBElement<CurveType2> createGmlProfileCurve(CurveType2 value) {
        return new JAXBElement<CurveType2>(_GmlProfileCurve_QNAME, CurveType2 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrientableCurvePropertyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.iho.int/s100gml/1.0", name = "orientableCurveProperty")
    public JAXBElement<OrientableCurvePropertyType> createOrientableCurveProperty(OrientableCurvePropertyType value) {
        return new JAXBElement<OrientableCurvePropertyType>(_OrientableCurveProperty_QNAME, OrientableCurvePropertyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InlinePropertyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/gml/3.2", name = "abstractInlineProperty")
    public JAXBElement<InlinePropertyType> createAbstractInlineProperty(InlinePropertyType value) {
        return new JAXBElement<InlinePropertyType>(_AbstractInlineProperty_QNAME, InlinePropertyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractCurveType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/gml/3.2", name = "AbstractCurve", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractGeometricPrimitive")
    public JAXBElement<AbstractCurveType> createAbstractCurve(AbstractCurveType value) {
        return new JAXBElement<AbstractCurveType>(_AbstractCurve_QNAME, AbstractCurveType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MultiPointType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.iho.int/s100gml/1.0", name = "MultiPoint", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractGeometricAggregate")
    public JAXBElement<MultiPointType> createGmlBaseMultiPoint(MultiPointType value) {
        return new JAXBElement<MultiPointType>(_GmlBaseMultiPoint_QNAME, MultiPointType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TitleEltType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1999/xlink", name = "title")
    public JAXBElement<TitleEltType> createTitle(TitleEltType value) {
        return new JAXBElement<TitleEltType>(_Title_QNAME, TitleEltType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/gml/3.2", name = "AbstractValue", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractObject")
    public JAXBElement<Object> createAbstractValue(Object value) {
        return new JAXBElement<Object>(_AbstractValue_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link S124NWPreambleType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.iho.int/S124/gml/1.0", name = "S124_NWPreamble", substitutionHeadNamespace = "http://www.iho.int/S124/gml/1.0", substitutionHeadName = "S124_InformationType")
    public JAXBElement<S124NWPreambleType> createS124NWPreamble(S124NWPreambleType value) {
        return new JAXBElement<S124NWPreambleType>(_S124NWPreamble_QNAME, S124NWPreambleType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.iho.int/S-100/profile/s100_gmlProfile", name = "complianceLevel")
    public JAXBElement<BigInteger> createComplianceLevel(BigInteger value) {
        return new JAXBElement<BigInteger>(_ComplianceLevel_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/gml/3.2", name = "AbstractScalarValue", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractValue")
    public JAXBElement<Object> createAbstractScalarValue(Object value) {
        return new JAXBElement<Object>(_AbstractScalarValue_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/gml/3.2", name = "reversePropertyName")
    public JAXBElement<String> createReversePropertyName(String value) {
        return new JAXBElement<String>(_ReversePropertyName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link S100ArcByCenterPointType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.iho.int/s100gml/1.0", name = "S100_ArcByCenterPoint", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractCurveSegment")
    public JAXBElement<S100ArcByCenterPointType> createS100ArcByCenterPoint(S100ArcByCenterPointType value) {
        return new JAXBElement<S100ArcByCenterPointType>(_S100ArcByCenterPoint_QNAME, S100ArcByCenterPointType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MultiPointType2 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/gml/3.2", name = "MultiPoint", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractGeometricAggregate")
    public JAXBElement<MultiPointType2> createMultiPoint(MultiPointType2 value) {
        return new JAXBElement<MultiPointType2>(_MultiPoint_QNAME, MultiPointType2 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReferenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/gml/3.2", name = "abstractReference")
    public JAXBElement<ReferenceType> createAbstractReference(ReferenceType value) {
        return new JAXBElement<ReferenceType>(_AbstractReference_QNAME, ReferenceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CurvePropertyType2 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/gml/3.2", name = "baseCurve")
    public JAXBElement<CurvePropertyType2> createBaseCurve(CurvePropertyType2 value) {
        return new JAXBElement<CurvePropertyType2>(_BaseCurve_QNAME, CurvePropertyType2 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InverseInformationAssociationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.iho.int/s100gml/1.0", name = "invInformationAssociation")
    public JAXBElement<InverseInformationAssociationType> createInvInformationAssociation(InverseInformationAssociationType value) {
        return new JAXBElement<InverseInformationAssociationType>(_InvInformationAssociation_QNAME, InverseInformationAssociationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/gml/3.2", name = "targetElement")
    public JAXBElement<String> createTargetElement(String value) {
        return new JAXBElement<String>(_TargetElement_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LocatorType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1999/xlink", name = "locator")
    public JAXBElement<LocatorType> createLocator(LocatorType value) {
        return new JAXBElement<LocatorType>(_Locator_QNAME, LocatorType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractGeometryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/gml/3.2", name = "AbstractGeometry", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractGML")
    public JAXBElement<AbstractGeometryType> createAbstractGeometry(AbstractGeometryType value) {
        return new JAXBElement<AbstractGeometryType>(_AbstractGeometry_QNAME, AbstractGeometryType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PointPropertyType2 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/gml/3.2", name = "pointMember")
    public JAXBElement<PointPropertyType2> createPointMember(PointPropertyType2 value) {
        return new JAXBElement<PointPropertyType2>(_PointMember_QNAME, PointPropertyType2 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrientableCurveType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/gml/3.2", name = "OrientableCurve", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractCurve")
    public JAXBElement<OrientableCurveType> createGmlProfileOrientableCurve(OrientableCurveType value) {
        return new JAXBElement<OrientableCurveType>(_GmlProfileOrientableCurve_QNAME, OrientableCurveType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PointPropertyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.iho.int/s100gml/1.0", name = "pointProperty")
    public JAXBElement<PointPropertyType> createPointProperty(PointPropertyType value) {
        return new JAXBElement<PointPropertyType>(_PointProperty_QNAME, PointPropertyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CompositeCurveType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.iho.int/s100gml/1.0", name = "CompositeCurve")
    public JAXBElement<CompositeCurveType> createGmlBaseCompositeCurve(CompositeCurveType value) {
        return new JAXBElement<CompositeCurveType>(_GmlBaseCompositeCurve_QNAME, CompositeCurveType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link S100CircleByCenterPointType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.iho.int/s100gml/1.0", name = "S100_CircleByCenterPoint", substitutionHeadNamespace = "http://www.iho.int/s100gml/1.0", substitutionHeadName = "S100_ArcByCenterPoint")
    public JAXBElement<S100CircleByCenterPointType> createS100CircleByCenterPoint(S100CircleByCenterPointType value) {
        return new JAXBElement<S100CircleByCenterPointType>(_S100CircleByCenterPoint_QNAME, S100CircleByCenterPointType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MultiPointPropertyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.iho.int/s100gml/1.0", name = "multiPointProperty")
    public JAXBElement<MultiPointPropertyType> createMultiPointProperty(MultiPointPropertyType value) {
        return new JAXBElement<MultiPointPropertyType>(_MultiPointProperty_QNAME, MultiPointPropertyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InformationPropertyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.iho.int/s100gml/1.0", name = "informationAssociation")
    public JAXBElement<InformationPropertyType> createInformationAssociation(InformationPropertyType value) {
        return new JAXBElement<InformationPropertyType>(_InformationAssociation_QNAME, InformationPropertyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RingType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/gml/3.2", name = "Ring", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractRing")
    public JAXBElement<RingType> createRing(RingType value) {
        return new JAXBElement<RingType>(_Ring_QNAME, RingType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CurveSegmentArrayPropertyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/gml/3.2", name = "segments")
    public JAXBElement<CurveSegmentArrayPropertyType> createSegments(CurveSegmentArrayPropertyType value) {
        return new JAXBElement<CurveSegmentArrayPropertyType>(_Segments_QNAME, CurveSegmentArrayPropertyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MeasureType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/gml/3.2", name = "measure")
    public JAXBElement<MeasureType> createMeasure(MeasureType value) {
        return new JAXBElement<MeasureType>(_Measure_QNAME, MeasureType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CurveType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.iho.int/s100gml/1.0", name = "Curve", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "Curve")
    public JAXBElement<CurveType> createCurve(CurveType value) {
        return new JAXBElement<CurveType>(_Curve_QNAME, CurveType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractSurfaceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/gml/3.2", name = "AbstractSurface", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractGeometricPrimitive")
    public JAXBElement<AbstractSurfaceType> createAbstractSurface(AbstractSurfaceType value) {
        return new JAXBElement<AbstractSurfaceType>(_AbstractSurface_QNAME, AbstractSurfaceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GeodesicStringType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/gml/3.2", name = "GeodesicString", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractCurveSegment")
    public JAXBElement<GeodesicStringType> createGeodesicString(GeodesicStringType value) {
        return new JAXBElement<GeodesicStringType>(_GeodesicString_QNAME, GeodesicStringType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/gml/3.2", name = "associationName")
    public JAXBElement<String> createAssociationName(String value) {
        return new JAXBElement<String>(_AssociationName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link S124FeatureTypeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.iho.int/S124/gml/1.0", name = "S124_FeatureType", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractFeature")
    public JAXBElement<S124FeatureTypeType> createS124FeatureType(S124FeatureTypeType value) {
        return new JAXBElement<S124FeatureTypeType>(_S124FeatureType_QNAME, S124FeatureTypeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PolygonType2 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/gml/3.2", name = "Polygon", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractSurface")
    public JAXBElement<PolygonType2> createPolygon(PolygonType2 value) {
        return new JAXBElement<PolygonType2>(_Polygon_QNAME, PolygonType2 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CompositeCurvePropertyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.iho.int/s100gml/1.0", name = "compositeCurveProperty")
    public JAXBElement<CompositeCurvePropertyType> createCompositeCurveProperty(CompositeCurvePropertyType value) {
        return new JAXBElement<CompositeCurvePropertyType>(_CompositeCurveProperty_QNAME, CompositeCurvePropertyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link S124InformationNoticePartType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.iho.int/S124/gml/1.0", name = "S124_InformationNoticePart", substitutionHeadNamespace = "http://www.iho.int/S124/gml/1.0", substitutionHeadName = "S124_InformationType")
    public JAXBElement<S124InformationNoticePartType> createS124InformationNoticePart(S124InformationNoticePartType value) {
        return new JAXBElement<S124InformationNoticePartType>(_S124InformationNoticePart_QNAME, S124InformationNoticePartType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PolygonPatchType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/gml/3.2", name = "PolygonPatch", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractSurfacePatch")
    public JAXBElement<PolygonPatchType> createPolygonPatch(PolygonPatchType value) {
        return new JAXBElement<PolygonPatchType>(_PolygonPatch_QNAME, PolygonPatchType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LineStringType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/gml/3.2", name = "LineString", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractCurve")
    public JAXBElement<LineStringType> createLineString(LineStringType value) {
        return new JAXBElement<LineStringType>(_LineString_QNAME, LineStringType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SurfaceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.iho.int/s100gml/1.0", name = "Surface", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "Surface")
    public JAXBElement<SurfaceType> createGmlBaseSurface(SurfaceType value) {
        return new JAXBElement<SurfaceType>(_GmlBaseSurface_QNAME, SurfaceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/gml/3.2", name = "Boolean", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractScalarValue")
    public JAXBElement<Boolean> createBoolean(Boolean value) {
        return new JAXBElement<Boolean>(_Boolean_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PointType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.iho.int/s100gml/1.0", name = "Point", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractGeometricPrimitive")
    public JAXBElement<PointType> createPoint(PointType value) {
        return new JAXBElement<PointType>(_Point_QNAME, PointType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GeodesicType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/gml/3.2", name = "Geodesic", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "GeodesicString")
    public JAXBElement<GeodesicType> createGeodesic(GeodesicType value) {
        return new JAXBElement<GeodesicType>(_Geodesic_QNAME, GeodesicType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AngleType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/gml/3.2", name = "angle")
    public JAXBElement<AngleType> createAngle(AngleType value) {
        return new JAXBElement<AngleType>(_Angle_QNAME, AngleType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CurvePropertyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.iho.int/s100gml/1.0", name = "curveProperty")
    public JAXBElement<CurvePropertyType> createCurveProperty(CurvePropertyType value) {
        return new JAXBElement<CurvePropertyType>(_CurveProperty_QNAME, CurvePropertyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArcType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.w3.org/1999/xlink", name = "arc")
    public JAXBElement<ArcType> createArc(ArcType value) {
        return new JAXBElement<ArcType>(_Arc_QNAME, ArcType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DirectPositionListType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/gml/3.2", name = "posList")
    public JAXBElement<DirectPositionListType> createPosList(DirectPositionListType value) {
        return new JAXBElement<DirectPositionListType>(_PosList_QNAME, DirectPositionListType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractCurveSegmentType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/gml/3.2", name = "AbstractCurveSegment", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractObject")
    public JAXBElement<AbstractCurveSegmentType> createAbstractCurveSegment(AbstractCurveSegmentType value) {
        return new JAXBElement<AbstractCurveSegmentType>(_AbstractCurveSegment_QNAME, AbstractCurveSegmentType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FeaturePropertyType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.iho.int/s100gml/1.0", name = "featureAssociation")
    public JAXBElement<FeaturePropertyType> createFeatureAssociation(FeaturePropertyType value) {
        return new JAXBElement<FeaturePropertyType>(_FeatureAssociation_QNAME, FeaturePropertyType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AbstractGeometricAggregateType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/gml/3.2", name = "AbstractGeometricAggregate", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractGeometry")
    public JAXBElement<AbstractGeometricAggregateType> createAbstractGeometricAggregate(AbstractGeometricAggregateType value) {
        return new JAXBElement<AbstractGeometricAggregateType>(_AbstractGeometricAggregate_QNAME, AbstractGeometricAggregateType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CurvePropertyType2 }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/gml/3.2", name = "curveMember")
    public JAXBElement<CurvePropertyType2> createCurveMember(CurvePropertyType2 value) {
        return new JAXBElement<CurvePropertyType2>(_CurveMember_QNAME, CurvePropertyType2 .class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EnvelopeType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.opengis.net/gml/3.2", name = "Envelope", substitutionHeadNamespace = "http://www.opengis.net/gml/3.2", substitutionHeadName = "AbstractObject")
    public JAXBElement<EnvelopeType> createEnvelope(EnvelopeType value) {
        return new JAXBElement<EnvelopeType>(_Envelope_QNAME, EnvelopeType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "id", scope = S124FeatureTypeType.class)
    public JAXBElement<String> createS124FeatureTypeTypeId(String value) {
        return new JAXBElement<String>(_S124FeatureTypeTypeId_QNAME, String.class, S124FeatureTypeType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PointCurveSurface }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "areaAffected", scope = S124FeatureTypeType.class)
    public JAXBElement<PointCurveSurface> createS124FeatureTypeTypeAreaAffected(PointCurveSurface value) {
        return new JAXBElement<PointCurveSurface>(_S124FeatureTypeTypeAreaAffected_QNAME, PointCurveSurface.class, S124FeatureTypeType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Float }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "radius", scope = S124FeatureTypeType.class)
    public JAXBElement<Float> createS124FeatureTypeTypeRadius(Float value) {
        return new JAXBElement<Float>(_S124FeatureTypeTypeRadius_QNAME, Float.class, S124FeatureTypeType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "extReferenceId", scope = S124FeatureTypeType.class)
    public JAXBElement<String> createS124FeatureTypeTypeExtReferenceId(String value) {
        return new JAXBElement<String>(_S124FeatureTypeTypeExtReferenceId_QNAME, String.class, S124FeatureTypeType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PointCurveSurface }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "geometry", scope = S124FeatureTypeType.class)
    public JAXBElement<PointCurveSurface> createS124FeatureTypeTypeGeometry(PointCurveSurface value) {
        return new JAXBElement<PointCurveSurface>(_S124FeatureTypeTypeGeometry_QNAME, PointCurveSurface.class, S124FeatureTypeType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "id", scope = S124InformationTypeType.class)
    public JAXBElement<String> createS124InformationTypeTypeId(String value) {
        return new JAXBElement<String>(_S124FeatureTypeTypeId_QNAME, String.class, S124InformationTypeType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ReferenceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "provides", scope = S124InformationTypeType.class)
    public JAXBElement<ReferenceType> createS124InformationTypeTypeProvides(ReferenceType value) {
        return new JAXBElement<ReferenceType>(_S124InformationTypeTypeProvides_QNAME, ReferenceType.class, S124InformationTypeType.class, value);
    }

}
