//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.03 at 12:29:04 PM GMT+01:00 
//


package stm.vis.data.area;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * Generalized feature type which carry all the common attributes
 * 
 * <p>Java class for S124_FeatureTypeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="S124_FeatureTypeType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.iho.int/s100gml/1.0}AbstractFeatureType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.iho.int/S124/gml/1.0}MRN" maxOccurs="unbounded"/>
 *         &lt;element name="extReferenceId" type="{http://www.iho.int/S124/gml/1.0}MRN" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="geometry" type="{http://www.iho.int/S124/gml/1.0}PointCurveSurface" maxOccurs="unbounded"/>
 *         &lt;element name="areaAffected" type="{http://www.iho.int/S124/gml/1.0}PointCurveSurface" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="radius" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "S124_FeatureTypeType", namespace = "http://www.iho.int/S124/gml/1.0", propOrder = {
    "rest"
})
@XmlSeeAlso({
    S124NavigationalWarningPartType.class
})
public abstract class S124FeatureTypeType
    extends AbstractFeatureType2
{

    @XmlElementRefs({
        @XmlElementRef(name = "areaAffected", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "geometry", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "extReferenceId", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "id", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "radius", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<?>> rest;

    /**
     * Gets the rest of the content model. 
     * 
     * <p>
     * You are getting this "catch-all" property because of the following reason: 
     * The field name "Id" is used by two different parts of a schema. See: 
     * line 116 of file:/tmp/schemas/area/S1241.xsd
     * line 36 of file:/tmp/schemas/area/S100_gmlProfile.xsd
     * <p>
     * To get rid of this property, apply a property customization to one 
     * of both of the following declarations to change their names: 
     * Gets the value of the rest property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rest property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRest().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link PointCurveSurface }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link Float }{@code >}
     * {@link JAXBElement }{@code <}{@link PointCurveSurface }{@code >}
     * 
     * 
     */
    public List<JAXBElement<?>> getRest() {
        if (rest == null) {
            rest = new ArrayList<JAXBElement<?>>();
        }
        return this.rest;
    }

}
