//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.03 at 12:29:04 PM GMT+01:00 
//


package stm.vis.data.area;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for S124_typeOfWarningType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="S124_typeOfWarningType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="local"/>
 *     &lt;enumeration value="coastal"/>
 *     &lt;enumeration value="sub-area"/>
 *     &lt;enumeration value="NAVAREA"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "S124_typeOfWarningType", namespace = "http://www.iho.int/S124/gml/1.0")
@XmlEnum
public enum S124TypeOfWarningType {

    @XmlEnumValue("local")
    LOCAL("local"),
    @XmlEnumValue("coastal")
    COASTAL("coastal"),
    @XmlEnumValue("sub-area")
    SUB_AREA("sub-area"),
    NAVAREA("NAVAREA");
    private final String value;

    S124TypeOfWarningType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static S124TypeOfWarningType fromValue(String v) {
        for (S124TypeOfWarningType c: S124TypeOfWarningType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
