//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.03 at 12:29:04 PM GMT+01:00 
//


package stm.vis.data.area;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 *  xxx 
 * 
 * <p>Java class for S124_NavigationalWarningPartType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="S124_NavigationalWarningPartType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.iho.int/S124/gml/1.0}S124_FeatureTypeType">
 *       &lt;sequence>
 *         &lt;element name="horizontalDatum" type="{http://www.iho.int/S124/gml/1.0}EPSGType" minOccurs="0"/>
 *         &lt;element name="Subject" type="{http://www.iho.int/S124/gml/1.0}S124_LocalizedTextType" minOccurs="0"/>
 *         &lt;element name="fixedDateRange" type="{http://www.iho.int/S124/gml/1.0}fixedDateRangeType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="header" type="{http://www.opengis.net/gml/3.2}ReferenceType"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "S124_NavigationalWarningPartType", namespace = "http://www.iho.int/S124/gml/1.0")
public class S124NavigationalWarningPartType
    extends S124FeatureTypeType
{


}
