//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.03 at 12:29:04 PM GMT+01:00 
//


package stm.vis.data.area;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for S124_affectedChartType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="S124_affectedChartType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="chartAffected" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="internationalChartAffected" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="language" type="{http://www.iho.int/S124/gml/1.0}ISO639-3" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "S124_affectedChartType", namespace = "http://www.iho.int/S124/gml/1.0", propOrder = {
    "chartAffected",
    "internationalChartAffected",
    "language"
})
public class S124AffectedChartType {

    @XmlElement(namespace = "")
    protected String chartAffected;
    @XmlElement(namespace = "")
    protected String internationalChartAffected;
    @XmlElement(namespace = "")
    protected String language;

    /**
     * Gets the value of the chartAffected property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChartAffected() {
        return chartAffected;
    }

    /**
     * Sets the value of the chartAffected property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChartAffected(String value) {
        this.chartAffected = value;
    }

    /**
     * Gets the value of the internationalChartAffected property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInternationalChartAffected() {
        return internationalChartAffected;
    }

    /**
     * Sets the value of the internationalChartAffected property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInternationalChartAffected(String value) {
        this.internationalChartAffected = value;
    }

    /**
     * Gets the value of the language property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanguage() {
        return language;
    }

    /**
     * Sets the value of the language property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLanguage(String value) {
        this.language = value;
    }

}
