//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.03 at 10:57:50 AM GMT+01:00 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.cirm.org/RTZ/1/1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package stm.vis.data.route;
