//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.03 at 10:34:56 AM GMT+01:00 
//


package stm.vis.data.textMessage;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for informationObjectTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="informationObjectTypeEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="RTZ"/>
 *     &lt;enumeration value="S124"/>
 *     &lt;enumeration value="TXT"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "informationObjectTypeEnum")
@XmlEnum
public enum InformationObjectTypeEnum {

    RTZ("RTZ"),
    @XmlEnumValue("S124")
    S_124("S124"),
    TXT("TXT");
    private final String value;

    InformationObjectTypeEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static InformationObjectTypeEnum fromValue(String v) {
        for (InformationObjectTypeEnum c: InformationObjectTypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
