/**
 * NOTE: This class is auto generated by the swagger code generator program (2.2.3).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package stm.vis.web.privateapi.api;

import java.util.List;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;
import stm.vis.web.privateapi.model.PublishedMessageContract;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2017-08-31T17:12:17.402Z")

@Api(value = "getPublishedMessages", description = "the getPublishedMessages API")
public interface GetPublishedMessagesApi {

	@ApiOperation(value = "Get all currently published messages", notes = "", response = PublishedMessageContract.class, responseContainer = "List", tags = {
			"PublishMessage", })
	@ApiResponses(value = {
			@ApiResponse(code = 200, message = "Success", response = PublishedMessageContract.class, responseContainer = "List"),
			@ApiResponse(code = 500, message = "Internal Server Error", response = Void.class),
			@ApiResponse(code = 200, message = "unexpected error", response = Void.class) })

	@RequestMapping(value = "/getPublishedMessages", produces = { "application/json" }, method = RequestMethod.GET)
	ResponseEntity<List<PublishedMessageContract>> publishMessageGetPublishedMessages();

}
